CREATE TABLE currency_pair (
	id int not null primary key generated by default as identity,
	base_charcode varchar(5),
	quoted_charcode varchar(5),
	description varchar(100)
);


CREATE TABLE exchange_rate (
	id bigint not null primary key generated by default as identity,
	rate_date timestamp,
	rate_value float,
	currency_pair_id int references currency_pair(id)
);

ALTER table currency_pair add constraint two_pairs_constraint UNIQUE (base_charcode, quoted_charcode);

--CREATE index exchange_rate_id_idx on exchange_rate (id);
CREATE index currency_pair_idx on currency_pair (base_charcode, quoted_charcode);

insert into currency_pair(base_charcode, quoted_charcode) values
	('AUD', 'AZN'),
	('AZN', 'AUD'),
	('USD', 'EUR'),
	('EUR', 'USD'),
	('RUR', 'USD'),
	('USD', 'RUR');

