--liquibase formatted sql

--changeset golov:1
CREATE TABLE IF NOT EXISTS currency_pair (
	id int not null primary key generated by default as identity,
	base_charcode varchar(5) NOT NULL,
	quoted_charcode varchar(5) NOT NULL,
	description varchar(100),
	constraint two_pairs_constraint UNIQUE (base_charcode, quoted_charcode)
);

--changeset golov:2
CREATE TABLE IF NOT EXISTS exchange_rate (
	id bigint not null primary key generated by default as identity,
	rate_date timestamp,
	rate_value float NOT NULL,
	currency_pair_id int references currency_pair(id)
);